version: "3.0"
services:
    mongo:
        image: mongo
        networks:
            net1:
                ipv4_address: 192.188.2.10
    amf:
        build: amf
        depends_on:
            - mongo
        networks:
            net1:
                ipv4_address: 192.188.2.2
    upf:
        build: upf
        privileged: true
        depends_on:
            - mongo
        networks:
            net1:
                ipv4_address: 192.188.2.6
            net2:
                ipv4_address: 45.45.0.2
    smf:
        build: smf
        depends_on:
            - mongo
            - upf
        networks:
            net1:
                ipv4_address: 192.188.2.4
            net2:
    hss:
        build: hss
        depends_on:
            - mongo
        networks:
            net1:
                ipv4_address: 192.188.2.3
    pcrf:
        build: pcrf
        depends_on:
            - mongo
        networks:
            net1:
                ipv4_address: 192.188.2.5
networks:
    net1:
        ipam:
            driver: default
            config:
                - subnet: "192.188.2.0/24"
    net2:
        ipam:
            driver: default
            config:
                - subnet: "45.45.0.0/24"
