version: "2.0"
services:
    mongo:
        image: mongo
        network_mode: "host"
    amf:
        build: .
        depends_on:
            - mongo
        network_mode: "host"
        command: ./bin/amf
    upf:
        build: upf
        privileged: true
        depends_on:
            - mongo
        devices:
              - "/dev/net/tun:/dev/net/tun"
        cap_add:
              - NET_ADMIN
        network_mode: "host"
    smf:
        build: .
        depends_on:
            - mongo
            - upf
        network_mode: "host"
        command: ./bin/smf
    ausf:
        build: .
        depends_on:
            - mongo
            - upf
        network_mode: "host"
        command: ./bin/ausf
    nrf:
        build: .
        depends_on:
            - mongo
            - upf
        network_mode: "host"
        command: ./bin/nrf
    nssf:
        build: .
        depends_on:
            - mongo
            - upf
        network_mode: "host"
        command: ./bin/nssf
    pcf:
        build: .
        depends_on:
            - mongo
            - upf
        network_mode: "host"
        command: ./bin/pcf
    udm:
        build: .
        depends_on:
            - mongo
            - upf
        network_mode: "host"
        command: ./bin/udm
    udr:
        build: .
        depends_on:
            - mongo
            - upf
        network_mode: "host"
        command: ./bin/udr
